#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <unistd.h>
#include <sys/socket.h>
#include <sys/un.h>
#include <stdbool.h>
#include <string.h>
#include <time.h>
#include "types.h"
#include "const.h"
#include "util.h"

// TODO: implement
int serial_binsearch(float list[], int n, int target) {
    int low = 0, mid, high = n-1; // define the lowest, mid and highest positions
    while (low <= high) {
         mid = (low + high) / 2;
         printf("low: %d mid: %d high: %d\n", low, mid, high);
         if (list[mid] < target) {
            low = mid + 1;
        }
         else if (list[mid] > target) {
            high = mid - 1;
        }
     }
     return mid;
    
}

// TODO: implement
int parallel_binsearch() {
    return 0;
}

int main(int argc, char** argv) {
    /* TODO: move this time measurement to right before the execution of each binsearch algorithms
     * in your experiment code. It now stands here just for demonstrating time measurement. */
    clock_t cbegin = clock();

    printf("[binsearch] Starting up...\n");

    /* Get the number of CPU cores available */
    printf("[binsearch] Number of cores available: '%ld'\n",
           sysconf(_SC_NPROCESSORS_ONLN));

    /* TODO: parse arguments with getopt */

    /* TODO: start datagen here as a child process. */

    /* TODO: implement code for your experiments using data provided by datagen and your
     * serial and parallel versions of binsearch.
     * */

    float list[11] = {0.5, 1.5, 3.5, 4.0, 5.1, 7.0, 10.32, 20.1, 100.2, 150.3, 200.02}; 

    printf("%d\n", serial_binsearch(list, 11, 200.02));

    /* TODO: connect to datagen and ask for the necessary data in each experiment round.
     * Create a Unix domain socket with DSOCKET_PATH (see const.h).
     * Talk to datagen using the messages specified in the assignment description document.
     * Read the values generated by datagen from the socket and use them to run your
     * experiments
     * */

    /* Probe time elapsed. */
    clock_t cend = clock();

    // Time elapsed in miliseconds.
    double time_elapsed = ((double) (cend - cbegin) / CLOCKS_PER_SEC) * 1000;

    printf("Time elapsed '%lf' [ms].\n", time_elapsed);

    exit(0);
}