#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <unistd.h>
#include <sys/socket.h>
#include <sys/un.h>
#include <stdbool.h>
#include <string.h>
#include <time.h>
#include "types.h"
#include "const.h"
#include "util.h"
#include <ctype.h>
#include <pthread.h>
#include <limits.h>
#include <signal.h>

int n;
unsigned int nums[100000000];
int target;
bool found = false;
int max_threads;
int part = 0;
// TODO: implement
bool serial_binsearch(unsigned int buf2[], int n) {
    int done = false;
    int low = 0, mid, high = n-1; // define the lowest, mid and highest positions
    while (low <= high && !done) {
         mid = (low + high) / 2;
         if (buf2[mid] < target) {
            low = mid + 1;
        }
         else if (buf2[mid] > target) {
            high = mid - 1;
        }
        else if (buf2[mid] == target)  {
            done = true;
            break;
        }
     }
     return done;  
}

// TODO: implement

void* parallel_binsearch(void* args) {
    part++;
    int thread_part = part;
    int mid;
    int low = thread_part * (n / max_threads);
    int high = (thread_part + 1) * (n / max_threads);
    while (low < high && !found)  {
        mid = (high - low) / 2 + low;
        if (nums[mid] == target && !found)  {
            found = true;
            break;
        }
        else if (nums[mid] > target)
            high = mid - 1;
        else
            low = mid + 1;
    }
    return NULL;
}

char *socket_path = "/tmp/dg.sock";;
int main(int argc, char** argv) {

    /* TODO: parse arguments with getopt */
    int E_value;
    int T_value;
    int P_value;

    int index;
    int c;

    opterr = 0;
    char  char_T_val[2] = "";
    if (argc == 1) {
        fprintf(stderr, "[binsearch] No arguments where given\n");
        exit(-2);
    }

    while( (c = getopt(argc, argv, "E:T:P:")) != -1) {
        switch(c) {
            case 'E':
                E_value = atoi(optarg);
                break;
            case 'T':
                strcpy(char_T_val, optarg);
                T_value = atoi(optarg);
                break;
            case 'P':
                P_value = atoi(optarg);
                break;
            case '?':
                if (isprint (optopt))
                    fprintf (stderr, "Unknown option `-%c'.\n", optopt);
                else
                    fprintf (stderr, "Unknown option character `\\x%x'.\n", optopt);
                return 1;
            default: 
                abort();
        }

    }

    /*Here we check that flag values are in the correct ranges*/
    if (E_value < 1) {
        fprintf(stderr, "[binsearch] Invalid value for E flag\n");
    }
    else if (T_value < 3 || T_value > 9) {
        fprintf(stderr, "[binsearch] Invalid value for T flag\n");
    }
    else if (P_value < 0 || P_value > pow(10, T_value) - 1) {
        fprintf(stderr, "[binsearch] Invalid value for P flag\n"); 
     }
    for (index = optind; index < argc; index++)
        printf ("[binsearch] Non-option argument %s\n", argv[index]);
    


    /* TODO: start datagen here as a child process. */
    int pid = fork();
    if (pid < 0) {
        perror("[binsearch] fork error.");
    }
    else if (pid == 0) {
        if (execv("./datagen", argv) < 0) {
            perror("[binsearch] execv error.");
            exit(-1);
        }
    }


    /* TODO: connect to datagen and ask for the necessary data in each experiment round.
     * Create a Unix domain socket with DSOCKET_PATH (see const.h).
     * Talk to datagen using the messages specified in the assignment description document.
     * Read the values generated by datagen from the socket and use them to run your
     * experiments
     * */
    
    // Variables
    struct sockaddr_un addr;
    int fd;
    n = pow(10, T_value); /*Amount of values in the array */

    if ( (fd = socket(AF_UNIX, SOCK_STREAM, 0)) == -1 ){
        perror("[binsearch] socket error");
        exit(-1);
    }

    memset(&addr, 0, sizeof(addr));
    addr.sun_family = AF_UNIX;


    strcpy(addr.sun_path, "/tmp/dg.sock");

    while ( connect(fd, (struct sockaddr*)&addr, sizeof(addr)) == -1){
        perror("[binsearch] connect error");
    }

    if ( connect(fd, (struct sockaddr*)&addr, sizeof(addr)) != -1){
        printf("[binsearch] connected");
    }

    // begin
    char starting_instruction[] = "BEGIN S ";
    strcat(starting_instruction, char_T_val); //instruccion completa de inicio
    if (write(fd, starting_instruction, sizeof(starting_instruction)) == -1) {
        perror("[binsearch] Error giving starting_instruction.");
        exit(-1);
    }
    // leo lo que me entrega el servidor
    long unsigned int readvalues = 0;
    size_t numvalues = pow(10, T_value);
    size_t readbytes = 0;

    UINT *readbuf = malloc(sizeof(UINT) * numvalues);
    while(readvalues < numvalues) {
        readbytes = read(fd, readbuf + readvalues, sizeof(UINT)*1000);
        readvalues += readbytes / 4;
    }

    if(write(fd, DATAGEN_END_CMD, sizeof(DATAGEN_END_CMD)) == -1){
        // AQUI DEBERIA TERMINAR EL PROCESO DEL DATAGEN Y SEGUIR CON LO DEL OUTPUT...
        perror("[binsearch] Error terminating datagen.");
        exit(-1);
    }

        //memset(buf, 0, sizeof(buf));
        //memset(buf2, 0, sizeof(buf2));

    max_threads = sysconf(_SC_NPROCESSORS_ONLN); /* Max amount of processors to be used */
    target = nums[P_value];
    
    printf("[binsearch] Starting up...\n");

    /* Get the number of CPU cores available */
    printf("[binsearch] Number of cores available: '%ld'\n", sysconf(_SC_NPROCESSORS_ONLN));

    /* TODO: implement code for your experiments using data provided by datagen and your
     * serial and parallel versions of binsearch.
     * */
    for(int i = 0; i < E_value - 1; i++) {
        struct timespec start, finish;
        double elapsed = 0;
        clock_gettime(CLOCK_MONOTONIC, &start);
        pthread_t threads[max_threads];
        for (int i = 0; i < max_threads; i++)
            pthread_create(&threads[i], NULL, parallel_binsearch, (void*)NULL);
     
        for (int i = 0; i < max_threads; i++)
            pthread_join(threads[i], NULL);
        clock_gettime(CLOCK_MONOTONIC, &finish);
        /* Probe time elapsed. */
        elapsed = (finish.tv_sec - start.tv_sec);
        elapsed += (finish.tv_nsec - start.tv_nsec) / 1000000000.0;


        struct timespec start_2, finish_2;
        double elapsed_2 = 0;
        clock_gettime(CLOCK_MONOTONIC, &start_2);
        serial_binsearch(nums, n);
        clock_gettime(CLOCK_MONOTONIC, &finish_2);
        elapsed_2 = (finish_2.tv_sec - start_2.tv_sec);
        elapsed_2 += (finish_2.tv_sec - start_2.tv_sec) / 1000000000.0;

        //printf("i = %d\n", i + 1);
        printf("%d,%d,%lf,%lf\n", E_value, T_value, elapsed_2, elapsed);
    }
    free(readbuf);
    exit(EXIT_SUCCESS);
}
